# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.1.0-stretch
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - add_ssh_keys
      - run:
          name: Fix ssh server host to ~/.ssh/known_hosts
          command: |
            ssh-keyscan 88.99.14.3 >> ~/.ssh/known_hosts

      - run:
          name: Install rsync
          command: sudo apt install -y rsync

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "client/package.json" }}-{{ checksum "server/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd client && yarn install
      - run: cd server && yarn install

      - save_cache:
          paths:
            - client/node_modules
            - server/node_modules
          key: v1-dependencies-{{ checksum "client/package.json" }}-{{ checksum "server/package.json" }}
        
      # run tests!
      - run: cd client && yarn test
      - run: cd client && yarn build

      - run:
          name: Deploy server/ to server
          command: |
            if [ $CIRCLE_BRANCH = 'master' ]; then
              cd server && yarn deploy
            fi
      - run:
          name: Deploy client/ to server
          command: |
            if [ $CIRCLE_BRANCH = 'master' ]; then
              cd client && yarn deploy
            fi

